import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync, existsSync } from "node:fs";
import esbuild from "esbuild";
import process from "process";

const outdir = "dist";
const outfile = `${outdir}/main.js`;

// Ensure dist directory exists
if (!existsSync(outdir)) {
	mkdirSync(outdir, { recursive: true });
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: outfile,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	// Copy manifest.json and styles.css to dist folder
	copyFileSync("manifest.json", `${outdir}/manifest.json`);
	copyFileSync("styles.css", `${outdir}/styles.css`);
	process.exit(0);
} else {
	await context.watch();
}
